name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '0.0.0'

permissions:
  contents: write
  id-token: write

jobs:
  create-release-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          npm run vscode:publish -- ${VERSION}
          git push
        env:
          VERSION: ${{ github.event.inputs.version }}
