name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version_to_increment:
        description: 'minor, patch, or major'
        required: true
        default: 'patch'
        options:
          - minor
          - patch
          - major

permissions:
  contents: write
  id-token: write

jobs:
  create-release-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          npm run vscode:publish -- ${VERSION_TO_INCREMENT}
          git push origin main
          git push origin `git describe --tags --abbrev=0`
        env:
          VERSION_TO_INCREMENT: ${{ github.event.inputs.version_to_increment }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
